version: "3.7"

services:
  ### Homepage: A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations ###
  homepage:
    image: ghcr.io/benphelps/homepage
    container_name: homepage
    restart: always
    environment:
      - TZ=${TZ}
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - traefik-network
    labels:
      ## Watchtower configuration ##
      - com.centurylinklabs.watchtower.enable=true

      ## Diun configuration ##
      - diun.enable=true

      ## Traefik configuration ##
      # Enable Traefik #
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      # Set entrypoint port #
      - traefik.http.services.homepage.loadbalancer.server.port=3000

      # Set HTTP domain and HTTP -> HTTPS redirection #
      - traefik.http.routers.homepage.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage.entrypoints=web
      - traefik.http.routers.homepage.middlewares=https-redirect@file

      # Set HTTPS domain #
      - traefik.http.routers.homepage-secure.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.homepage-secure.entrypoints=websecure
      - traefik.http.routers.homepage-secure.middlewares=authelia@docker

networks:
  default:
    name: homepage-network
  traefik-network:
    name: traefik-network
    external: true
